import { entityPageUrl } from '../api/planningData';
import { classifyChecked, impactTier, TIER_LABELS } from '../datasets';
import { DATA_GAPS } from '../dataGaps';
import type { PlansheetReport, ReportData, ScoredHit } from '../types';

export const REPORT_DISCLAIMER =
  'Generated by PlanSheet from the MHCLG Planning Data platform. Not a substitute for a formal ' +
  'local land charges search or pre-application advice. Datasets vary in completeness by authority; ' +
  'see coverageIncomplete and notCovered.';

function hitName(hit: ScoredHit): string {
  const name = String(hit.entity.name ?? '').trim();
  if (name !== '') return name;
  if (hit.registry.slug === 'title-boundary') {
    return `Registered title (INSPIRE ${hit.entity.reference || hit.entity.entity})`;
  }
  return hit.entity.reference || `Entity ${hit.entity.entity}`;
}

function optionalString(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() !== '' ? value : undefined;
}

/**
 * Serialise a plan sheet to the stable, versioned {@link PlansheetReport} schema
 * (SPEC-03) — for AI appraisal pipelines, storage, and the future MCP server.
 */
export function reportToJson(data: ReportData): PlansheetReport {
  const adminHits = data.hits.filter((h) => h.registry.category === 'administrative');
  const constraintHits = data.hits.filter((h) => h.registry.category !== 'administrative');
  const { clear, partialNoData } = classifyChecked(data.checked, data.hits, data.failedDatasets);

  return {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    location: {
      latitude: data.selection.lat,
      longitude: data.selection.lng,
      label: data.selection.label ?? null,
      nearestPostcode: data.nearestPostcode,
    },
    ...(data.site
      ? {
          site: {
            areaSquareMetres: Math.round(data.site.areaM2),
            areaHectares: Number((data.site.areaM2 / 10000).toFixed(4)),
            geometry: data.site.geojson,
          },
        }
      : {}),
    ...(data.nearby
      ? {
          nearby: {
            radiusMetres: data.nearby.radiusM,
            skippedDatasets: data.nearby.skippedDense,
            hits: data.nearby.hits.map((h) => ({
              dataset: h.registry.slug,
              label: h.registry.label,
              name: hitName(h),
              entity: h.entity.entity,
              url: entityPageUrl(h.entity.entity),
              category: h.registry.category,
              impactScore: h.score,
              impactTier: TIER_LABELS[impactTier(h.score)],
              distanceMetres: Math.round(h.distanceM),
              bearing: h.bearing,
              qualifier: h.qualifier,
            })),
          },
        }
      : {}),
    administrative: adminHits.map((h) => ({
      dataset: h.registry.slug,
      label: h.registry.label,
      name: hitName(h),
      reference: h.entity.reference ?? '',
      entity: h.entity.entity,
      url: entityPageUrl(h.entity.entity),
    })),
    constraints: constraintHits.map((h) => {
      const cov = data.coverage?.get(h.entity.entity);
      return {
        dataset: h.registry.slug,
        label: h.registry.label,
        name: hitName(h),
        reference: h.entity.reference ?? '',
        entity: h.entity.entity,
        url: entityPageUrl(h.entity.entity),
        category: h.registry.category,
        impactScore: h.score,
        impactTier: TIER_LABELS[impactTier(h.score)],
        qualifier: h.qualifier,
        detail: h.detail,
        startDate: optionalString(h.entity['start-date']),
        entryDate: optionalString(h.entity['entry-date']),
        organisation: optionalString(h.entity['organisation-entity']),
        ...(cov !== undefined
          ? {
              siteCoverage:
                cov === null
                  ? ('n/a' as const)
                  : { percent: Number(cov.pct.toFixed(1)), areaSquareMetres: Math.round(cov.areaM2) },
            }
          : {}),
      };
    }),
    coverageIncomplete: partialNoData.map((c) => ({ dataset: c.slug, label: c.label })),
    checkedClear: clear.map((c) => ({ dataset: c.slug, label: c.label })),
    couldNotCheck: data.failedDatasets,
    notCovered: DATA_GAPS.map((g) => ({ topic: g.topic, why: g.why, whereToCheck: g.whereToCheck })),
    disclaimer: REPORT_DISCLAIMER,
  };
}
